# Generated by Django 3.1.1 on 2020-09-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=2, max_length=13),
            preserve_default=False,
        ),
    ]
